language: ruby
cache: bundler
services:
- postgresql
before_script:
- psql -c 'create database operationcode_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:migrate
- RAILS_ENV=test bundle exec rake db:test:prepare
deploy:
  provider: heroku
  api_key:
    secure: IjVV/RT2ewpGGM3/lX3mjEzroHzKWVNMKQJTQK/i/z2dOA2bmxFHvqLP1cvuiW7LAyzvCiIbTflDr1kyIQnBUlIfHWgQCwAFbhL74FxnNYznZ6eDovtlkV9a/2Xq6CEX0BdFtbyGEXWto+zqO+R0iXEZ4suaswzRxKBde4RXG1I=
  app: opcod3
  on:
    repo: OperationCode/operationcode
notifications:
  slack:
    secure: iT5O6nPXUfThuPLhLXY1q6iNPrJfXxwv78ZynDiZZ2HjUqk98F7LTLY4dAXabbPL2w4hY9YcE8gTXch5n+eyjIaCSNHiR6VMJuxdhiw7uolAy5F71rEMyhNmZbe7X+lqNTp5GpoBUU2oCrT3Hh30lE8Z3c1XrQ+hvm0vh7Y1hXs=
