default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
  host: operationcode-psql

development:
  <<: *default
  database: operationcode_development
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>

test:
  <<: *default
  database: operationcode_test
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>

production:
  <<: *default
  database: operationcode_production
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
